# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger:
- master

resources:
- repo: self
pool:
  name: new
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Scan
    displayName: Scan
    steps:
    - task: HCLAppScanOnCloud@2
      inputs:
        AppSecTestService: 'HCL AppScan'
        applications: '6fec47ad-f8cb-461a-ba42-b867e8929a72'
        scanname: 'azure-test'
        scantype: 'static'
        scanloc: 'C:\Users\Sam\Downloads\eShopOnWeb-master\eShopOnWeb-master'
