# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger:
- master

resources:
- repo: self
pool:
  name: new
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/.devcontainer/Dockerfile'
        tags: |
          $(tag)
    - task: HCLAppScanOnCloud@2
      inputs:
        AppSecTestService: 'HCL AppScan'
        applications: '6fec47ad-f8cb-461a-ba42-b867e8929a72'
        scanname: 'azure-test'
        scantype: 'static'
